const $=s=>document.querySelector(s);let token=sessionStorage.getItem('clank-token')||'',current=null,data=null;
const key=()=>crypto.randomUUID();
async function api(path,opts={}){const r=await fetch('/api/v1'+path,{...opts,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,...(opts.method&&opts.method!=='GET'?{'Idempotency-Key':key()}:{}),...opts.headers}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||r.statusText);return j}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function fmt(t){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(t))}
function showApp(on){$('#login').classList.toggle('hidden',on);$('#app').classList.toggle('hidden',!on);$('#logout').classList.toggle('hidden',!on)}
async function boot(){if(!token)return showApp(false);try{await api('/whoami');showApp(true);await projects()}catch{sessionStorage.removeItem('clank-token');token='';showApp(false)}}
async function projects(){const j=await api('/projects'),items=j.projects||[];const n=$('#projects');n.innerHTML=items.map(p=>`<button data-id="${p.id}" class="${current===p.id?'active':''}">${esc(p.name)}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>openProject(b.dataset.id));if(!current&&items[0])openProject(items[0].id)}
async function openProject(id){current=id;data=await api('/projects/'+id);$('#empty').classList.add('hidden');$('#project-view').classList.remove('hidden');$('#project-slug').textContent=data.project.slug;$('#project-name').textContent=data.project.name;$('#project-description').textContent=data.project.description||'No project description yet.';render();projects()}
function render(){const notes=data.notes||[];$('#note-count').textContent=notes.length+' records';$('#notes').innerHTML=notes.length?notes.map(noteCard).join(''):'<div class="item"><p>No accrued intent yet.</p></div>';$('#notes').querySelectorAll('.supersede').forEach(b=>b.onclick=()=>supersede(b.dataset.id,+b.dataset.rev));const tr=data.trajectories||[];$('#trajectories').innerHTML=tr.length?tr.map(trajectoryCard).join(''):'<div class="item"><p>No active trajectories.</p></div>';const repos=data.repositories||[];$('#repositories').innerHTML=repos.length?repos.map(repoCard).join(''):'<div class="item"><p>No repository attached.</p></div>'}
function provenance(n){const r=n.run;if(!r)return'';return [r.harness,r.provider,r.model,r.role,r.runType].filter(Boolean).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}
function noteCard(n){const lifecycle=n.status==='current'?`<button class="supersede" data-id="${n.id}" data-rev="${n.revision}">Supersede</button>`:`<span class="status">${esc(n.status)}</span>`;return `<article class="item">${lifecycle}<span class="kind">${esc(n.kind)} · ${esc(n.ledBy)}</span><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p>${n.rationale?`<p><strong>Why:</strong> ${esc(n.rationale)}</p>`:''}<div class="meta">${provenance(n)}${(n.paths||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}<span class="pill">${fmt(n.updatedAt)}</span></div></article>`}
function trajectoryCard(t){return `<article class="item"><span class="kind">${esc(t.status)} trajectory</span><h3>${esc(t.objective)}</h3>${t.rationale?`<p>${esc(t.rationale)}</p>`:''}<div class="meta">${provenance(t)}${(t.paths||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div></article>`}
function repoCard(r){return `<article class="item repo"><a href="${r.url}" target="_blank" rel="noreferrer">${esc(r.owner+'/'+r.name)} ↗</a><p>${esc(r.description||'Public GitHub repository')}</p>${(r.pullRequests||[]).map(p=>`<a class="pr" href="${p.url}" target="_blank" rel="noreferrer">#${p.externalId} ${esc(p.title)}</a>`).join('')}</article>`}
function modal(title,fields,onSave){$('#dialog-fields').innerHTML=`<h2>${esc(title)}</h2>`+fields;const d=$('#dialog');d.showModal();$('#dialog-form').onsubmit=async e=>{e.preventDefault();try{await onSave(new FormData(e.target));d.close()}catch(x){toast(x.message)}}}
$('#login-form').onsubmit=async e=>{e.preventDefault();token=$('#token').value.trim();sessionStorage.setItem('clank-token',token);boot()};$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};
$('#new-project').onclick=()=>modal('New project','<label>Name<input name="name" required></label><label>Slug<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required></label><label>Description<textarea name="description"></textarea></label>',async f=>{await api('/projects',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await projects();toast('Project created')});
$('#add-note').onclick=()=>modal('Record accrued intent','<label>Kind<select name="kind"><option>intent</option><option>decision</option><option>understanding</option><option>observation</option><option>checkpoint</option></select></label><label>Title<input name="title" maxlength="180" required></label><label>Project-relevant summary<textarea name="summary" maxlength="1200" required></textarea></label><label>Rationale<textarea name="rationale" maxlength="2400"></textarea></label><label>Led by<select name="ledBy"><option>human</option><option>joint</option><option>agent</option><option>external</option></select></label><label>Direction basis<select name="directionBasis"><option>explicit_human_direction</option><option>interpreted_human_intent</option><option>joint_reasoning</option><option>autonomous_agent_judgment</option><option>external_evidence</option></select></label><label>Paths (comma-separated)<input name="paths"></label>',async f=>{const o=Object.fromEntries(f);o.paths=o.paths.split(',').map(x=>x.trim()).filter(Boolean);await api(`/projects/${current}/notes`,{method:'POST',body:JSON.stringify(o)});await openProject(current);toast('Context recorded')});
async function supersede(id,rev){const reason=prompt('Why is this context no longer current?');if(!reason)return;await api(`/projects/${current}/notes/${id}/supersede`,{method:'POST',body:JSON.stringify({expectedRevision:rev,reason})});await openProject(current);toast('Context superseded')}
$('#brief-form').onsubmit=async e=>{e.preventDefault();const objective=$('#brief-objective').value,paths=$('#brief-paths').value.split(',').map(x=>x.trim()).filter(Boolean);const b=await api(`/projects/${current}/brief`,{method:'POST',body:JSON.stringify({objective,paths,checkConflicts:true})});$('#warnings').innerHTML=b.coordinationWarnings?.length?b.coordinationWarnings.map(w=>`<div class="warning"><strong>${esc(w.summary)}</strong><p>${esc(w.reason)}</p>${w.trajectory?`<p>Related trajectory: ${esc(w.trajectory.objective)}</p>`:''}<div class="options">Options: ${w.options.join(' · ')}</div></div>`).join(''):'<div class="item"><p>No intersecting active trajectory found. This is a context check, not proof of safety.</p></div>';$('#warnings').scrollIntoView({behavior:'smooth',block:'center'})};$('#run-brief').onclick=()=>$('#brief-form').requestSubmit();
$('#attach-repo').onclick=()=>modal('Attach public GitHub repository','<label>Repository URL<input name="url" placeholder="https://github.com/owner/repo" required></label>',async f=>{await api(`/projects/${current}/repositories`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await openProject(current);toast('Repository attached')});
boot();
$('#agent-key').onclick=()=>modal('Issue a project agent key','<p>This identity represents agents working for this project. The secret is shown once.</p><label>Identity name<input name="displayName" placeholder="shuv2code agents"></label>',async f=>{const credential=await api(`/projects/${current}/tokens`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});setTimeout(()=>modal('Copy this key now',`<p>${esc(credential.notice)}</p><label>Project agent token<input value="${esc(credential.token)}" readonly></label>`,async()=>{}),80)});
